export default function TermsPage() {
  return <main className="legal-page">
    <a href="/">← Voltar ao Hub Brasil</a><span className="eyebrow">REGRAS DA PLATAFORMA</span><h1>Termos de Uso</h1><p>Última atualização: 13 de agosto de 2026.</p>
    <h2>1. Objetivo</h2><p>O Hub Brasil conecta profissionais e fornecedores do mercado de rastreamento veicular. A plataforma atua como diretório e vitrine gratuita, não vende produtos, não processa pagamentos e não participa das negociações realizadas entre usuários.</p>
    <h2>2. Cadastro, verificação e contato</h2><p>O participante deve fornecer informações verdadeiras e manter seus dados atualizados. Ao concluir o cadastro e aceitar estes Termos, autoriza expressamente o Hub Brasil a entrar em contato pelo telefone, WhatsApp ou e-mail informado para confirmar a identidade do usuário, validar o telefone e o cadastro, solicitar correções, comunicar o andamento da análise, prevenir fraude e verificar a experiência de navegação na plataforma. Esse contato não autoriza o envio de publicidade sem fundamento legal adequado.</p>
    <h2>3. Aprovação</h2><p>Fornecedores passam por validação de telefone e aprovação antes de publicar conteúdo. O prazo estimado de análise de cadastros, produtos e eventos é de até 24 horas em dias úteis, contado após o recebimento completo das informações. O prazo poderá ser ampliado quando houver necessidade de verificação adicional, indisponibilidade técnica ou grande volume de solicitações.</p>
    <h2>4. Produtos e eventos</h2><p>O fornecedor é responsável pela exatidão e autorização de uso de fotos, marcas, especificações, aplicações, diferenciais, datas, locais e links. Todo conteúdo pode ser revisado, recusado, editado ou removido pela gestão. A aprovação não representa certificação técnica, garantia de qualidade ou recomendação comercial do fornecedor.</p>
    <h2>5. Avaliações</h2><p>Cada pessoa identificada pode manter uma avaliação por fornecedor. Manipulação, perfis falsos, avaliações em troca de vantagem, conteúdo ofensivo ou conflitos de interesse não declarados podem resultar em remoção e bloqueio.</p>
    <h2>6. Condutas proibidas</h2><p>É proibido publicar conteúdo ilegal, falso, enganoso ou discriminatório, violar direitos de terceiros, usar contatos para spam, tentar acessar áreas restritas, coletar dados de forma automatizada ou interferir na segurança da plataforma.</p>
    <h2>7. Proteção dos dados</h2><p>Os dados serão tratados e protegidos conforme a Política de Privacidade e a legislação aplicável. O Hub Brasil aplica medidas de controle de acesso e segurança, mas nenhum sistema é totalmente imune a riscos.</p>
    <h2>8. Negociações, preços e responsabilidade</h2><p>O Hub Brasil possui exclusivamente a função de aproximar e conectar fornecedores e clientes. Não participa das negociações, não define, recomenda ou garante preços, não realiza cobranças e não processa pagamentos. Valores, ofertas, disponibilidade, frete, condições comerciais, garantias e formas de pagamento devem ser confirmados diretamente entre as partes. O Hub Brasil não responde por divergências de valores, ofertas, pagamentos, qualidade, entrega, realização de eventos ou descumprimento de obrigações por terceiros. Usuários devem realizar sua própria verificação comercial antes de contratar, comprar ou efetuar pagamentos.</p>
    <h2>9. Suspensão</h2><p>Cadastros e conteúdos podem ser corrigidos, suspensos ou removidos para proteger a comunidade, cumprir a lei, investigar suspeitas de fraude ou fazer cumprir estes Termos.</p>
    <h2>10. Hub Créditos e destaques</h2><p>Hub Créditos são pontos virtuais promocionais internos, sem valor monetário. Não são transferíveis, sacáveis ou conversíveis em dinheiro, PIX, cashback, brindes, descontos, produtos ou qualquer benefício financeiro. Quando disponíveis, servem exclusivamente para recursos de visibilidade dentro do Hub Brasil. Créditos não alteram o Hub Score, avaliações, verificações ou reputação do fornecedor.</p><p>O Hub Brasil poderá cancelar créditos, destaques ou participações obtidos por fraude, abuso, duplicidade, informações falsas, tentativa de manipulação ou violação destes Termos. Destaques são temporários, identificados na plataforma e dependem de elegibilidade, aprovação e qualidade mínima.</p>
    <h2>11. Contato</h2><p>Dúvidas, solicitações e assuntos relacionados à privacidade podem ser encaminhados para <a href="mailto:suporte@niviontech.com.br">suporte@niviontech.com.br</a>.</p>
  </main>;
}
