"use client";
import { FormEvent, useEffect, useState } from "react";
type Community = { role:"client"|"supplier"; needs:Array<{id:number;category:string;title:string;description:string;city:string;state:string;deadline?:string|null}>; updates:Array<{id:number;title:string;content:string;link?:string|null}>; articles:Array<{id:number;title:string;summary:string;category:string;author:string;sourceType:string}> };
const categories=["Rastreadores","Plataformas de rastreamento veicular","Conectividade M2M","Câmeras veiculares","Tags e identificação","Acessórios"];
export default function CommunityTests(){
 const [data,setData]=useState<Community|null>(null),[error,setError]=useState(""),[message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/community");const j=await r.json();if(r.status===401&&j.signIn){location.href=j.signIn;return}if(!r.ok){setError(j.error);return}setData(j)}
 useEffect(()=>{load()},[]);
 async function send(payload:Record<string,unknown>,ok:string){setError("");const r=await fetch("/api/community",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok){setError(j.error);return}setMessage(ok);await load()}
 function need(e:FormEvent<HTMLFormElement>){e.preventDefault();send({action:"create_need",...Object.fromEntries(new FormData(e.currentTarget))},"Demanda enviada para aprovação.")}
 function update(e:FormEvent<HTMLFormElement>){e.preventDefault();send({action:"create_update",...Object.fromEntries(new FormData(e.currentTarget))},"Novidade enviada para aprovação.")}
 return <main className="test-area"><header className="test-header"><div><span>HUB BRASIL · COMUNIDADE EM TESTE</span><h1>Conexões e conteúdo</h1><p>Demandas não exibem telefone. O cliente decide quando compartilhar contato.</p></div><a href="/area-testes">Voltar aos testes</a></header>{error&&<div className="test-feedback error">{error}</div>}{message&&<div className="test-feedback success">{message}</div>}{!data?<div className="test-loading">Carregando…</div>:<div className="test-grid">
 <section className="test-card wide"><div className="test-card-title"><div><small>MURAL PROTEGIDO</small><h2>Estou procurando</h2></div><span>⌕</span></div>{data.needs.length===0?<p className="test-empty">Nenhuma demanda aprovada no momento.</p>:<div className="community-grid">{data.needs.map(n=><article key={n.id}><span>{n.category}</span><h3>{n.title}</h3><p>{n.description}</p><small>{n.city}/{n.state}</small>{data.role==="supplier"&&<button onClick={()=>send({action:"interest",needId:n.id,message:prompt("Mensagem breve para o cliente:")||"Tenho interesse nesta necessidade."},"Interesse registrado. O cliente continua no controle do contato.")}>Tenho interesse</button>}</article>)}</div>}</section>
 {data.role==="client"?<section className="test-card"><div className="test-card-title"><div><small>CLIENTE</small><h2>Publicar necessidade</h2></div><span>＋</span></div><form className="test-form" onSubmit={need}><label>Título<input name="title" required maxLength={120}/></label><label>Categoria<select name="category" required><option value="">Selecione</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Descrição<textarea name="description" rows={4} required/></label><div className="test-row"><label>Cidade<input name="city" required/></label><label>Estado<input name="state" maxLength={2} required/></label></div><label>Prazo<input name="deadline" type="date"/></label><div className="consent-box">Seu telefone não aparecerá no mural. A publicação será revisada pela gestão.</div><button>Enviar para aprovação</button></form></section>:<section className="test-card"><div className="test-card-title"><div><small>FORNECEDOR</small><h2>Publicar novidade</h2></div><span>✦</span></div><form className="test-form" onSubmit={update}><label>Título<input name="title" required maxLength={120}/></label><label>Conteúdo<textarea name="content" rows={5} required/></label><label>Link opcional<input name="link" type="url"/></label><div className="consent-box">Somente fornecedores verificados podem enviar novidades. Toda publicação passa por aprovação.</div><button>Enviar para aprovação</button></form></section>}
 <section className="test-card"><div className="test-card-title"><div><small>VITRINE</small><h2>Novidades aprovadas</h2></div><span>✦</span></div>{data.updates.length===0?<p className="test-empty">Nenhuma novidade publicada.</p>:data.updates.map(u=><article className="content-item" key={u.id}><h3>{u.title}</h3><p>{u.content}</p>{u.link&&<a href={u.link} target="_blank" rel="noreferrer">Saiba mais →</a>}</article>)}</section>
 <section className="test-card wide"><div className="test-card-title"><div><small>CONHECIMENTO</small><h2>Central de conteúdo técnico</h2></div><span>▤</span></div>{data.articles.length===0?<p className="test-empty">A central está pronta para receber guias revisados.</p>:<div className="community-grid">{data.articles.map(a=><article key={a.id}><span>{a.category} · {a.sourceType==="editorial"?"Editorial":"Fornecedor"}</span><h3>{a.title}</h3><p>{a.summary}</p><small>Por {a.author}</small></article>)}</div>}</section>
 </div>}</main>}
